import bpy
from pathlib import Path

# Make `pxr` module available, for running as `bpy` PIP package.
bpy.utils.expose_bundled_modules()

from pxr import Usd, UsdGeom
from typing import List
from . import constants

def get_datablock_from_prim(blender_prim: Usd.Prim) -> dict:
    name = None

    if blender_prim.HasProperty("userProperties:blender:object_name"):
        name = blender_prim.GetProperty("userProperties:blender:object_name").Get()

    if blender_prim.HasProperty("userProperties:blender:data_name"):
        name = blender_prim.GetProperty("userProperties:blender:data_name").Get()

    if not name:
        return

    data_block_type = constants.get_datablock_type(blender_prim.GetTypeName())
    if data_block_type:
        return data_block_type.get(name)

def has_source_prim(blender_prim: Usd.Prim, source_stage: Usd.Stage) -> bool:
    """Check if the given Blender prim has a corresponding source prim in the source stage.

    Args:
        blender_prim (Usd.Prim): Prim Exported by Blender
        source_stage (Usd.Stage): Source USD Stage

    Returns:
        bool: True if the source prim exists, False otherwise
    """
    bl_data_block = get_datablock_from_prim(blender_prim)
    if bl_data_block and hasattr(bl_data_block, "usd_connect_props"):
        source_prim_path = bl_data_block.usd_connect_props.prim_path
        source_prim = source_stage.GetPrimAtPath(source_prim_path)
        if source_prim and source_prim.IsValid():
            return source_prim
    return False

def get_all_prims(stage:Usd.Stage) -> List[Usd.Prim]:
    """Get all prims in the stage, except for those autogenerated by Blender like "root".

    Args:
        stage (Usd.Stage): The USD stage to traverse.

    Returns:
        List[Usd.Prim]: A list of all non-generated prims in the stage.
    """
     # Filter out prims autogenerated by Blender like "root"
    all_prims : List[Usd.Prim] = []
    for bl_prim in stage.Traverse():
        if bl_prim.HasCustomDataKey("Blender"):
            if bl_prim.GetCustomDataByKey("Blender")["generated"] == True:
                continue
        all_prims.append(bl_prim)
    return all_prims


def get_matching_prims(source_stage:Usd.Stage, blender_prims:List[Usd.Prim]) -> dict[Usd.Prim, Usd.Prim]:
    """Get a mapping of matching prims between the source stage and Blender exported prims.

    Args:
        source_stage (Usd.Stage): The source USD stage to compare against.
        blender_prims (List[Usd.Prim]): The list of Blender exported prims.

    Returns:
        dict[Usd.Prim, Usd.Prim]: A mapping of matching prims between the source stage and Blender exported prims.
    """
    # Find all prims that match a path in the source stage
    matched_blender_prims: dict[Usd.Prim, Usd.Prim] = {}

    for bl_prim in blender_prims:
        # Find matching prim in source stage
        source_prim = has_source_prim(bl_prim, source_stage)
        if source_prim:
            matched_blender_prims[bl_prim] = source_prim

    return matched_blender_prims    


def override_property(
    src_prim: Usd.Prim, trg_prop: Usd.Property, override_stage: Usd.Stage
):
    src_prop = src_prim.GetProperty(trg_prop.GetName())

    if not src_prop:
        print(f"PROP: Missing '{trg_prop.GetName()}' on '{src_prim.GetPath()}'")
        return

    if hasattr(src_prop, "GetTargets"):
        # Special Property Handling
        if src_prop.GetTargets() != trg_prop.GetTargets():
            override_prim = override_stage.OverridePrim(src_prim.GetPath())
            override_prim.GetProperty(trg_prop.GetName()).SetTargets(
                trg_prop.GetTargets()
            )
            print(f"PROP: Overrided  '{trg_prop.GetName()}' on '{src_prim.GetPath()}'")
            return

    # Skip attributes that don't have get (relationships AFAIK)
    if hasattr(trg_prop, "Get"):
        if src_prop.Get() != trg_prop.Get():
            override_prim = override_stage.OverridePrim(src_prim.GetPath())
            override_prim.GetProperty(trg_prop.GetName()).Set(trg_prop.Get())
            print(f"PROP: Overrided '{trg_prop.GetName()}' on '{src_prim.GetPath()}'")
            return


def override_attribute(
    src_prim: Usd.Prim, trg_attr: Usd.Attribute, override_stage: Usd.Stage
):
    if src_prim.HasAttribute(trg_attr.GetName()):
        if src_prim.GetAttribute(trg_attr.GetName()).Get() != trg_attr.Get():
            override_prim = override_stage.OverridePrim(src_prim.GetPath())
            override_prim.GetAttribute(trg_attr.GetName()).Set(trg_attr.Get())
            print(f"ATTR: Overrided '{trg_attr.GetName()}' on '{src_prim.GetPath()}'")
    else:
        override_prim = override_stage.OverridePrim(src_prim.GetPath())
        # Attribute doesn't exist on source prim, add it
        override_prim.CreateAttribute(trg_attr.GetName(), trg_attr.GetTypeName()).Set(
            trg_attr.Get()
        )
        print(f"ATTR: Created '{trg_attr.GetName()}' on '{src_prim.GetPath()}'")


def override_prim_attributes_and_properties(
    blender_prim: Usd.Prim, source_prim: Usd.Prim, override_stage: Usd.Stage
) -> None:
    """Override the attribute of a prim in the override stage if it differs from the source stage.

    Args:
        blender_prim (Usd.Prim): The Blender exported prim.
        source_prim (Usd.Prim): The source prim to compare against.
        override_stage (Usd.Stage): The override stage to apply changes to.
    """
    # TODO Handle in a more generic way and support other attributes
    # This is good for demo purposes, but not a general solution

    for bl_attr in blender_prim.GetAttributes():
        override_attribute(source_prim, bl_attr, override_stage)

    for bl_prop in blender_prim.GetProperties():
        # If Property exists on source prim and value is different, override it
        override_property(source_prim, bl_prop, override_stage)


def get_unmatched_prims(blender_prims:List[Usd.Prim], matched_blender_prims:dict[Usd.Prim, Usd.Prim]) -> List[Usd.Prim]:
    """Get a list of unmatched Blender prims.

    Args:
        blender_prims (List[Usd.Prim]): List of Blender exported prims.
        matched_blender_prims (dict[Usd.Prim, Usd.Prim]): A mapping of matching prims between Blender exported prims as keys and source prim as values.

    Returns:
        List[Usd.Prim]: A list of unmatched Blender prims.
    """
    return list(set(blender_prims) - set(matched_blender_prims.keys()))


def generate_usd_overrides_for_prims(source_stage:Usd.Stage, override_stage:Usd.Stage, bl_stage:Usd.Stage) -> None:
    # Filter out prims autogenerated by Blender like "root"
    blender_prims = get_all_prims(bl_stage)

    # Collect all the relevant prims
    matched_prims = get_matching_prims(source_stage, blender_prims)
    unmatched_prims = get_unmatched_prims(blender_prims, matched_prims)

    # Figure out if prims have been modified
    for bl_prim, src_prim in matched_prims.items():
        # check_matching_prims(bl_prim, src_prim)
        override_prim_attributes_and_properties(bl_prim, src_prim, override_stage)

    for unmatched in unmatched_prims:
        print(f"PRIM: Skipped Unmatched: {unmatched.GetPath()}")

def generate_usd_override_file(bl_stage: Usd.Stage) -> None:
    # Create Stage to Generate Overrides onto
    bl_stage_path = Path(bl_stage.GetRootLayer().realPath)
    override_stage_path = bl_stage_path.parent.joinpath(
        "layer_" + bl_stage_path.name
    ).as_posix()
    override_stage = Usd.Stage.CreateNew(override_stage_path)

    for library in bpy.context.scene.usd_connect_libraries:
        # Add reference to source stage in override file
        source_stage = Usd.Stage.Open(library.file_path)
        source_stage_path = Path(source_stage.GetRootLayer().realPath).as_posix()
        override_stage.GetRootLayer().subLayerPaths.append(source_stage_path)

        generate_usd_overrides_for_prims(   
            source_stage=source_stage,
            override_stage=override_stage,
            bl_stage=bl_stage,
        )

    override_stage.Save()
